### ISSUE TITLE
Gtk-WARNING **: 09:53:52.943: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg

### ISSUE THREAD

**Issue by TheYoctoManju** [intgr/ego#151]
root@imx8mp-lpddr4-evk:~# paprefs

(paprefs:1751): Gtk-WARNING **: 09:53:52.943: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
root@imx8mp-lpddr4-evk:~# pavucontrol

(pavucontrol:1772): Gtk-WARNING **: 09:54:09.895: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
unable to fix this issue, Target board is imx8mplus evk

**Comment by intgr** [comment]
Please explain what you are trying to do and how you are using `ego`.

**Comment by TheYoctoManju** [comment]
Using yocto i have created image for IMX8m Plus EVK with build (imx-image-full). The Goal is to get simultaneous audio play on two paired Bluetooth devices on the target board.
So to achieve this i have included paprefs and pavucontrol for pulseaudio, so that from paprefs i can set simultaneous audio playback on two paired devices. 
Even if i set tick mark to simultaneous audio play in paprefs, Pavucontrol does not show any for simultaneous Play.
i think if i fix that warning the issue may resolve.
And also i noticed that there must be module called module-combine-sink to sink the devices. which was checked on host machine on Ubuntu 22.04.3 LTS  ls /usr/lib/pulse-15.99.1+dfsg1/modules/.
but that is missing on my target machine IMX8M plus evk with this build.
I tried to copy (module-combine-sink ) and reboot the target, it didn't work.
I need solution to achieve the goal.

**Comment by intgr** [comment]
You reported this issue to the `ego` project. https://github.com/intgr/ego You haven't explained how any of this is related to ego.

If you have issues with `paprefs` or `pavucontrol`, report it to *their* issue tracker instead.
