### ISSUE TITLE
GUI for password prompt

### ISSUE THREAD

**Issue by kiwec** [intgr/ego#57]
First of all, thanks for making this.

I'm currently using it with an i3 fork that changes the border based on the user that owns the window. This makes ego really useful for GUI apps, since I can just call `ego --user=xxx dmenu_run` to start something as another user, and have a light sandbox that's more convenient than running Qubes OS (and also loses most of the security benefits, lol).

But, when you're using ego outside of a terminal, you can't see the password prompt. It would be great to add a password prompt window (my lazy self thinks of using the `dialog` utility, but that's an external dependency).

Any thoughts on this?

**Comment by intgr** [comment]
Sounds reasonable. The `machinectl` method should be capable of calling an askpass agent, which can create a GUI password prompt. But I would have to research a bit how it works.

Feel free to remind me about this if I don't reply in a few days.

**Comment by intgr** [comment]
Hi kiwec. I looked into this a bit:

1. ego's `machinectl` mode authenticates via Polkit. All you need to do is to have some GUI Polkit authentication agent running in your desktop session. Not sure what distro you're using, but here's a list of agents for Arch Linux: https://wiki.archlinux.org/title/Polkit#Authentication_agents

2. For ego's `sudo` mode I have created PR #58 to enable using the `SUDO_ASKPASS` environment variable with ego. Here's an example how to set up `zenity` GUI password prompt with it: https://askubuntu.com/questions/314395/proper-way-to-let-user-enter-password-for-a-bash-script-using-only-the-gui-with

3. Alternatively, you can forego the password prompt entirely if you follow the instructions about [Avoid password prompt](https://github.com/intgr/ego#avoid-password-prompt) from ego's README.

Do these solve your use case?

**Comment by intgr** [comment]
Closing this. Feel free to re-open if you think there is something more that ego could do.
