### ISSUE TITLE
No sound in sudo mode?

### ISSUE THREAD

**Issue by Hooloovoo** [intgr/ego#60]
Hello,

I am using Ubuntu 20.04 with Wayland. My use case is that I have a work and personal account and want to run a window of Firefox as my personal user (with all my bookmarks, history etc) in my work session.

I ran:
`sudo apt install libacl1-dev
cargo install ego
sudo cp ~/.cargo/bin/ego /usr/local/bin/
sudo useradd ego --uid 155 --create-home
ego -u [username]-personal firefox`

It gives the following warnings:
`warning: machinectl (systemd-container) is not installed
warning: Falling back to 'sudo', some desktop integration features may not work`

Firefox seems to be working fine (I'm using it now), but I have no sound, which is the problem I was trying to solve with ego over and above running firefox using xhost and sudo manually. Does sound to pulseaudio only work with "machinectl" mode?

**Comment by Hooloovoo** [comment]
Ha. Idiot. Ignore me -- I still had a window open the old way. Closing all my windows and starting again with ego worked as expected with sound. Thanks for the great tool!

**Comment by intgr** [comment]
Thanks for the feedback, always great to hear when people find this useful. :)
