### ISSUE TITLE
Signal-Desktop fails to start as a second user

### ISSUE THREAD

**Issue by Hooloovoo** [intgr/ego#61]
I was hoping to run two instances of Signal-Desktop, one as my work account/phone number and one as my personal account/phone number, but the second instance will not start.

```
$ ego -u [user] signal-desktop
warning: machinectl (systemd-container) is not installed
warning: Falling back to 'sudo', some desktop integration features may not work
[sudo] password for [user]: 
mkdir: cannot create directory '/run/user/1000': Permission denied
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/364/opt/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/[snap]/snap/signal-desktop/364/.config/Signal
config/get: Successfully read user config file
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
x-attr dependency did not load successfully
config/get: Successfully read ephemeral config file
making app single instance
quitting; we are the second instance
```

It looks like I'm using the snap version of Signal-Desktop.

**Comment by intgr** [comment]
Any ideas what mechanism Signal-Desktop uses to detect single session?

**Comment by Hooloovoo** [comment]
No, unfortunately, though this:
https://github.com/signalapp/Signal-Desktop/issues/3420
talks about some of the checks.

**Comment by intgr** [comment]
I just tried this and I'm able to run two copies of signal-desktop simultaneously using `ego`, using either `--sudo` or `--machinectl` mode.

<img src="https://user-images.githubusercontent.com/137616/124988481-b7263880-e046-11eb-9974-f03725846d4f.png" width="411" height="366" />

So there is something else going on here. Maybe snap interfering?

I noticed in your output:

> mkdir: cannot create directory '/run/user/1000': Permission denied

Is UID 1000 your primary user ID or the ego target user?

**Comment by Hooloovoo** [comment]
Ah yes... Interesting. Switching to debs, this works fine. 

1000 here is the UID of the ego target rather than the account I'm running it from (which is 1001). I will close this as my problem is solved, though feel free to reopen it if you are interested in debugging the issue (happy to reinstall the snap to debug).
