### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by machinexa2** [intgr/ego#63]
Compiling atty v0.2.14
   Compiling users v0.11.0
   Compiling posix-acl v1.0.0
23   Compiling clap_derive v3.0.0-beta.4
   Compiling clap v3.0.0-beta.4
error: unexpected token: `include_str`
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^

error: aborting due to previous error

error: failed to compile `ego v1.1.2`, intermediate artifacts can be found at `/tmp/cargo-installCDXbBy`

Caused by:
  could not compile `clap`.

To learn more, run the command again with --verbose.

from cargo install ego

**Comment by intgr** [comment]
Hi! Looks like `clap-3.0.0-beta.4` has started using new features added in Rust 1.54.

You should be able to build with the older locked dependency version, using `cargo build --locked`

**Comment by intgr** [comment]
Apart from the two suggestions above, I don't think there's anything I can do about this.
