### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by Fabioah** [intgr/ego#65]
Hi, I'm getting the following errors 

` Compiling ego v1.1.2
error[E0599]: no variant or associated item named `DisableVersion` found for enum `AppSettings` in the current scope
  --> /home/fabio/.cargo/registry/src/github.com-1ecc6299db9ec823/ego-1.1.2/src/cli.rs:23:31
   |
23 |         .setting(AppSettings::DisableVersion)
   |                               ^^^^^^^^^^^^^^
   |                               |
   |                               variant or associated item not found in `AppSettings`
   |                               help: there is a variant with a similar name: `DisableVersionFlag`

error[E0599]: no variant or associated item named `ColoredHelp` found for enum `AppSettings` in the current scope
  --> /home/fabio/.cargo/registry/src/github.com-1ecc6299db9ec823/ego-1.1.2/src/cli.rs:24:31
   |
24 |         .setting(AppSettings::ColoredHelp)
   |                               ^^^^^^^^^^^ variant or associated item not found in `AppSettings`

For more information about this error, try `rustc --explain E0599`.
error: failed to compile `ego v1.1.2`, intermediate artifacts can be found at `/tmp/cargo-installYiEjMx`

Caused by:
  could not compile `ego` due to 2 previous errors
`
I'm using rust 1.55.0 on gentoo since the stable version was giving errors during clap compile.

**Comment by intgr** [comment]
Ahh looks like `clap` has changed their API. That's what I get for using the alpha version :)

Thanks for letting me know, I'll try to fix soon.

**Comment by intgr** [comment]
Actually, as a workaround, you can use `cargo install ego --locked`, which uses locked dependency versions.

**Comment by Fabioah** [comment]
Thank you. Using cargo install ego --locked worked.

**Comment by intgr** [comment]
Upstream issue: https://github.com/rust-lang/cargo/issues/7169
