### ISSUE TITLE
Can't run any program

### ISSUE THREAD

**Issue by Fabioah** [intgr/ego#66]
Hi, I get this error every time I try to launch a program with ego

> Setting up Alter Ego for user ego (155)
> error: Error preparing X11: No such file or directory (os error 2)

I am on Gentoo using Sway and Wayland with Xwyaland installed. I do not have xorg installed.

**Comment by intgr** [comment]
Hi! Sorry, I forgot to respond to this.

You need the the `xhost` binary installed (`/usr/bin/xhost`). I'm not sure which Gentoo package it corresponds to. If installing that doesn't fix it, let me know.

**Comment by intgr** [comment]
The error message from `ego` definitely needs improvement though.

**Comment by Fabioah** [comment]
Thank you. I thought xhost was required just for X11.

**Comment by intgr** [comment]
Yeah, xhost is still needed if you have Xwayland. It's not needed if the `DISPLAY` environment variable is unset.

I also noticed also that this requirement isn't documented in README.

**Comment by intgr** [comment]
I documented the `xhost` requirement and improved error reporting of xhost in #76. Hopefully this will avoid similar confusion in the future.
